In [24]:
# Import necessary modules and libraries

import pandas as pd
from pandas import DataFrame as df
import os
import tkinter as tk
from tkinter import filedialog, messagebox

In [25]:
#open the input (csv) file
root = tk.Tk()
root.withdraw()
root.attributes("-topmost", True)
messagebox.showinfo('BIOMASS', 'Open the input file with extracted GIS data ')
input_file = filedialog.askopenfilename()
#path = r"C:\GHANA"
#name_of_file = "GHANA_Updated.csv"

In [26]:
# Import csv as pandas dataframe
input = pd.read_csv(input_file)
country ='Ghana'

In [27]:
#viewing your dataframe
input.head()

,NightLights,Pop,id,GridCellArea,ElecPop,WindVel,GHI,TravelHours,Elevation,Slope,...,CurrentMVLineDist,RoadDist,X_deg,Y_deg,TransformerDist,PlannedMVLineDist,PlannedHVLineDist,HydropowerDist,Hydropower,HydropowerFID
0,39174.0,16.289471,39174,0.018,0.000000,137.169052,4.402690,34.053467,25.308851,0.450712,...,395.441,1.576,-1.366528,10.677799,0.0,395.441,17.103,22.499143,163.220,66.0
1,39176.0,6.499694,39176,0.009,6.499694,392.352386,4.996162,33.976733,10.754715,1.048877,...,370.057,2.593,-0.837778,10.677799,0.0,370.057,2.793,49.985679,124.531,64.0
2,39175.0,16.289471,39175,0.009,16.289471,200.835724,4.562789,34.102183,13.181263,0.131793,...,393.838,0.981,-1.336944,10.677799,0.0,393.838,18.072,25.630491,163.220,66.0
3,39170.0,222.254126,39170,0.147,0.000000,231.121445,4.890044,34.327417,45.097161,0.204339,...,429.102,1.523,-2.802726,10.678531,0.0,429.102,28.487,11.112183,163.747,74.0
4,39169.0,16.289471,39169,0.018,0.000000,98.709518,4.728223,34.125383,20.000000,0.452100,...,389.079,2.919,-1.244444,10.679049,0.0,389.079,19.296,35.528327,255.197,65.0

In [5]:
input.columns

Index(['NightLights', 'Pop', 'id', 'GridCellArea', 'ElecPop', 'WindVel', 'GHI',
       'TravelHours', 'Elevation', 'Slope', 'ResidentialDemandTIerCustom',
       'LandCover', 'SubstationDist', 'CurrentHVLineDist', 'CurrentMVLineDist',
       'RoadDist', 'X_deg', 'Y_deg', 'TransformerDist', 'PlannedMVLineDist',
       'PlannedHVLineDist', 'HydropowerDist', 'Hydropower', 'HydropowerFID',
       'acof', 'bana', 'barl', 'bean', 'cass', 'chic', 'cnut', 'coco', 'cott',
       'cow_p', 'grou', 'lent', 'maiz', 'ocer', 'ofib', 'oilp', 'ooil', 'opul',
       'orts', 'pige', 'plnt', 'pmil', 'pota', 'rape', 'rcof', 'rest', 'rice',
       'sesa', 'smil', 'sorg', 'soyb', 'sugb', 'sugc', 'sunf', 'swpo', 'teas',
       'temf', 'toba', 'trof', 'vege', 'whea', 'yams'],
      dtype='object')

In [6]:
input_subset=df(input,columns= ['acof', 'bana', 'barl', 'bean', 'cass', 'chic', 'cnut', 'coco', 'cott',
       'cow_p', 'grou', 'lent', 'maiz', 'ocer', 'ofib', 'oilp', 'ooil', 'opul',
       'orts', 'pige', 'plnt', 'pmil', 'pota', 'rape', 'rcof', 'rest', 'rice',
       'sesa', 'smil', 'sorg', 'soyb', 'sugb', 'sugc', 'sunf', 'swpo', 'teas',
       'temf', 'toba', 'trof', 'vege', 'whea', 'yams'])
input_subset.head()

,acof,bana,barl,bean,cass,chic,cnut,coco,cott,cow_p,...,sugc,sunf,swpo,teas,temf,toba,trof,vege,whea,yams
0,0.0,0.0,0.0,55.4,0.0,0.0,0.0,0.0,17.7,0.0,...,0.0,0.0,1713.90002,0.0,113.20000,0.0,0.00000,81.40000,0.0,0.0
1,0.0,0.0,0.0,297.0,0.0,0.0,0.0,0.0,28.9,0.0,...,0.0,0.0,3011.89990,0.0,119.10000,29.7,0.00000,571.90002,0.0,0.0
2,0.0,0.0,0.0,55.4,0.0,0.0,0.0,0.0,17.7,0.0,...,0.0,0.0,1713.90002,0.0,113.20000,0.0,0.00000,81.40000,0.0,0.0
3,0.0,0.0,0.0,22.8,0.0,0.0,0.0,0.0,21.8,0.0,...,1.7,0.0,0.00000,0.0,84.10000,0.0,257.20001,1440.30005,0.0,0.0
4,0.0,0.0,0.0,64.3,0.0,0.0,0.0,0.0,35.2,0.0,...,0.0,0.0,2203.69995,0.0,162.10001,0.0,0.00000,272.60001,0.0,0.0

In [7]:
#residue-product-ratio (RPR)
#suggestion:maybe make this column as a seperate excel sheet and import as a dataframe
#REFERENCES:
    #Khatiwada, D., Purohit, P., Ackom, E.K., 2019. Mapping Bioenergy Supply and Demand in Selected Least Developed Countries (LDCs): Exploratory Assessment of Modern Bioenergyâ€™s Contribution to SDG7. Sustainability 11, e7091. https://doi.org/Khatiwada D, Purohit P <http://pure.iiasa.ac.at/view/iiasa/239.html> ORCID: https://orcid.org/0000-0002-7265-6960 <https://orcid.org/0000-0002-7265-6960>, & Ackom EK  (2019).  Mapping Bioenergy Supply and Demand in Selected Least Developed Countries (LDCs): Exploratory Assessment of Modern Bioenergyâ€™s Contribution to SDG7.   Sustainability 11 (24): e7091. DOI:10.3390/su11247091 <https://doi.org/10.3390/su11247091>.
    #Okello, C., Pindozzi, S., Faugno, S., Lorenzo, B., 2013. Bioenergy potential of agricultural and forest residues in Uganda. Biomass Bioenergy 56. https://doi.org/10.1016/j.biombioe.2013.06.003
    #http://www.fao.org/3/AD576E/ad576e00.pdf
#assumptions:
#beans,lentils,peas=pulses ; othercereals==barley
#other fibre=jute ; otheroilcrops==palm oil ;other roots,yam ==potatoes
#plantain==banana ;rapeseed,sunflower==groudnut; restofcrops=2; rapeseed==groudnut

acof=1
bana=2
barl=1.3
bean=1.4
cass=0.88
chic=1.4
cnut=1.6
#coco
cott=1.1
cow_p=2.9
grou=2.1
lent=1.4
maiz=2.5
ocer= 1.3
ofib=2
oilp=0.24
ooil=0.24
opul=1.4
orts=0.25
pige=5
plnt=2
pmil=1.4
pota=0.25
rape= 2.1
rcof=1
rest=2
rice=1.8
sesa=2
smil=1.2
sorg=1.4
soyb=2.66
sugb=0.7
sugc=0.4
sunf=2.1
swpo=0.25
#teas=
temf=2
toba=0.2
trof=2
vege=1
whea=1.6
yams=0.25

In [8]:
#compute the residuals in tonnes. The unit is stated here:https://www.mapspam.info/methodology/
input_subset['acof']=input_subset['acof']*acof
input_subset['bana']=input_subset['bana']*bana
input_subset['barl']=input_subset['barl']*barl
input_subset['bean']=input_subset['bean']*bean
input_subset['cass']=input_subset['cass']*cass
input_subset['chic']=input_subset['chic']*chic
input_subset['cnut']=input_subset['cnut']*cnut
input_subset['cott']=input_subset['cott']*cott
input_subset['cow_p']=input_subset['cow_p']*cow_p
input_subset['grou']=input_subset['grou']*grou
input_subset['lent']=input_subset['lent']*lent
input_subset['maiz']=input_subset['maiz']*maiz
input_subset['ocer']=input_subset['ocer']*ocer
input_subset['ofib']=input_subset['ofib']*ofib
input_subset['oilp']=input_subset['oilp']*oilp
input_subset['ooil']=input_subset['ooil']*ooil
input_subset['opul']=input_subset['opul']*opul
input_subset['orts']=input_subset['orts']*orts
input_subset['pige']=input_subset['pige']*pige
input_subset['plnt']=input_subset['plnt']*plnt
input_subset['pmil']=input_subset['pmil']*pmil
input_subset['pota']=input_subset['pota']*pota
input_subset['rape']=input_subset['rape']*rape
input_subset['rcof']=input_subset['rcof']*rcof
input_subset['rest']=input_subset['rest']*rest
input_subset['rice']=input_subset['rice']*rice
input_subset['sesa']=input_subset['sesa']*sesa
input_subset['smil']=input_subset['smil']*smil
input_subset['sorg']=input_subset['sorg']*sorg
input_subset['soyb']=input_subset['soyb']*soyb
input_subset['sugb']=input_subset['sugb']*sugb
input_subset['sugc']=input_subset['sugc']*sugc
input_subset['sunf']=input_subset['sunf']*sunf
input_subset['swpo']=input_subset['swpo']*swpo
input_subset['temf']=input_subset['temf']*temf
input_subset['toba']=input_subset['toba']*toba
input_subset['trof']=input_subset['trof']*trof
input_subset['vege']=input_subset['vege']*vege
input_subset['whea']=input_subset['whea']*whea
input_subset['yams']=input_subset['yams']*yams

In [9]:
#adding the technical potential in tonnes 
technical_potential=input_subset['technical_potential']=input_subset.sum(axis=1)
print("The total bioenergy technical potential in {} is {:.3f} million tonnes".format(country,(technical_potential.sum(axis=0))/1000000))

The total bioenergy technical potential in Ghana is 4438.331 million tonnes

In [10]:
#calculation for bioelectricty potential
annual_full_load_hours =5600    #unit is hours
specific_biomass=0.00121           #unit is ton/kWh
specific_bagasse=0.0016            #unit is ton/kWh
elec_potential_coefficient=0.2  #assumption for agricultiral residues available for electricity production in the least developing countries
capacity_factor_biomass=0.8
capacity_factor_bagasse=0.53
biomass_subset=df(input_subset,columns= ['acof', 'bana', 'barl', 'bean', 'cass', 'chic', 'cnut', 'coco', 'cott',
       'cow_p', 'grou', 'lent', 'maiz', 'ocer', 'ofib', 'oilp', 'ooil', 'opul',
       'orts', 'pige', 'plnt', 'pmil', 'pota', 'rape', 'rcof', 'rest', 'rice',
       'sesa', 'smil', 'sorg', 'soyb', 'sunf', 'swpo', 'teas',
       'temf', 'toba', 'trof', 'vege', 'whea', 'yams'])
#bagasse_subset=df(input_subset,columns=['sugb', 'sugc']) --this was not used
biomass_subset[:] *=(elec_potential_coefficient/specific_biomass)
bioelec_potential_kWh=biomass_subset['bioelec_potential_kWh']=biomass_subset.sum(axis=1)
print("The total bioelectricity potential in {} is {:.3f} TWh".format(country,(bioelec_potential_kWh.sum(axis=0))/1000000000))

The total bioelectricity potential in Ghana is 733.126 TWh

In [11]:
#adding the bioelectricy_potential column to the original dataset and dropping the infomation of the individual criops
input=df(input,columns=['NightLights', 'Pop', 'id', 'GridCellArea', 'ElecPop', 'WindVel', 'GHI',
       'TravelHours', 'Elevation', 'Slope', 'ResidentialDemandTIerCustom',
       'LandCover', 'SubstationDist', 'CurrentHVLineDist', 'CurrentMVLineDist',
       'RoadDist', 'X_deg', 'Y_deg', 'TransformerDist', 'PlannedMVLineDist',
       'PlannedHVLineDist', 'HydropowerDist', 'Hydropower', 'HydropowerFID','bioelec_potential_kWh'])
input['bioelec_potential_kWh']=biomass_subset['bioelec_potential_kWh']

input.head()

,NightLights,Pop,id,GridCellArea,ElecPop,WindVel,GHI,TravelHours,Elevation,Slope,...,RoadDist,X_deg,Y_deg,TransformerDist,PlannedMVLineDist,PlannedHVLineDist,HydropowerDist,Hydropower,HydropowerFID,bioelec_potential_kWh
0,39174,16.289471,39174,0.018,0.000000,137.169052,4.402690,34.053467,25.308851,0.450712,...,1.576,-1.366528,10.677799,0,395.441,17.103,22.499143,163.220,66,1.241082e+06
1,39176,6.499694,39176,0.009,6.499694,392.352387,4.996162,33.976733,10.754715,1.048877,...,2.593,-0.837778,10.677799,0,370.057,2.793,49.985679,124.531,64,1.985940e+06
2,39175,16.289471,39175,0.009,16.289471,200.835724,4.562789,34.102183,13.181263,0.131793,...,0.981,-1.336944,10.677799,0,393.838,18.072,25.630491,163.220,66,1.241082e+06
3,39170,222.254126,39170,0.147,0.000000,231.121445,4.890044,34.327417,45.097161,0.204339,...,1.523,-2.802726,10.678531,0,429.102,28.487,11.112183,163.747,74,2.490519e+06
4,39169,16.289471,39169,0.018,0.000000,98.709518,4.728223,34.125383,20.000000,0.452100,...,2.919,-1.244444,10.679049,0,389.079,19.296,35.528327,255.197,65,1.868631e+06

In [23]:
#input['bio_new']= input['bioelec_potential_kWh'].divide(annual_full_load_hours) 
#input.head()

,NightLights,Pop,id,GridCellArea,ElecPop,WindVel,GHI,TravelHours,Elevation,Slope,...,X_deg,Y_deg,TransformerDist,PlannedMVLineDist,PlannedHVLineDist,HydropowerDist,Hydropower,HydropowerFID,bioelec_potential_kWh,bio_new
0,39174,16.289471,39174,0.018,0.000000,137.169052,4.402690,34.053467,25.308851,0.450712,...,-1.366528,10.677799,0,395.441,17.103,22.499143,163.220,66,1.241082e+06,221.621752
1,39176,6.499694,39176,0.009,6.499694,392.352387,4.996162,33.976733,10.754715,1.048877,...,-0.837778,10.677799,0,370.057,2.793,49.985679,124.531,64,1.985940e+06,354.632079
2,39175,16.289471,39175,0.009,16.289471,200.835724,4.562789,34.102183,13.181263,0.131793,...,-1.336944,10.677799,0,393.838,18.072,25.630491,163.220,66,1.241082e+06,221.621752
3,39170,222.254126,39170,0.147,0.000000,231.121445,4.890044,34.327417,45.097161,0.204339,...,-2.802726,10.678531,0,429.102,28.487,11.112183,163.747,74,2.490519e+06,444.735538
4,39169,16.289471,39169,0.018,0.000000,98.709518,4.728223,34.125383,20.000000,0.452100,...,-1.244444,10.679049,0,389.079,19.296,35.528327,255.197,65,1.868631e+06,333.684037

In [27]:
output='Output'

In [28]:
messagebox.showinfo('OnSSET', 'Browse to the folder where you want to save the outputs')
output_dir = filedialog.askdirectory()
output_dir_output = os.path.join(output_dir, '{}_Results.csv'.format(output))

In [29]:
# Returning the result as a csv file
input.to_csv(output_dir_output, index=False)