In [1]:
# Import necessary modules and libraries

import pandas as pd
from pandas import DataFrame as df
import os
import tkinter as tk
from tkinter import filedialog, messagebox

In [2]:
#open the input (csv) file
root = tk.Tk()
root.withdraw()
root.attributes("-topmost", True)
messagebox.showinfo('BIOMASS', 'Open the input file with extracted GIS data ')
input_file = filedialog.askopenfilename()
#path = r"C:\GHANA"
#name_of_file = "GHANA_Updated.csv"

In [3]:
# Import csv as pandas dataframe
input = pd.read_csv(input_file)
country ='Somalia'

In [4]:
#viewing your dataframe
input.head()

,Country,NightLights,Pop,id,GridCellArea,ElecPop,WindVel,GHI,TravelHours,Elevation,...,sugc,sunf,swpo,teas,temf,toba,trof,vege,whea,yams
0,Somalia,0.0,65.015217,8956,0.013,0.0,7.573399,2254.000000,6.650000,9.179685,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Somalia,0.0,14368.362920,10117,0.906,0.0,7.415857,2252.768695,6.619415,4.779344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Somalia,0.0,195.045650,8954,0.053,0.0,7.197120,2250.000000,6.550000,6.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Somalia,0.0,32.507608,878,0.009,0.0,7.674210,2246.000000,6.450000,11.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Somalia,0.0,130.030434,10111,0.018,0.0,7.490109,2245.000000,6.366667,8.000000,...,5.9,0.0,145.300003,0.0,0.0,0.0,6.6,451.299988,0.0,0.0

In [5]:
input.columns

Index(['Country', 'NightLights', 'Pop', 'id', 'GridCellArea', 'ElecPop',
       'WindVel', 'GHI', 'TravelHours', 'Elevation', 'Slope',
       'ResidentialDemandTierCustomDemand', 'LandCover', 'SubstationDist',
       'CurrentHVLineDist', 'CurrentMVLineDist', 'RoadDist', 'X_deg', 'Y_deg',
       'TransformerDist', 'PlannedMVLineDist', 'PlannedHVLineDist',
       'HydropowerDist', 'Hydropower', 'HydropowerFID', 'acof', 'bana', 'barl',
       'bean', 'cass', 'chic', 'cnut', 'coco', 'cott', 'cow_p', 'grou', 'lent',
       'maiz', 'ocer', 'ofib', 'oilp', 'ooil', 'opul', 'orts', 'pige', 'plnt',
       'pmil', 'pota', 'rape', 'rest', 'rcof', 'rice', 'sesa', 'smil', 'sorg',
       'soyb', 'sugb', 'sugc', 'sunf', 'swpo', 'teas', 'temf', 'toba', 'trof',
       'vege', 'whea', 'yams'],
      dtype='object')

In [7]:
input.fillna(0,inplace=True)

In [8]:
input_subset=df(input,columns= ['acof', 'bana', 'barl', 'bean', 'cass', 'chic', 'cnut', 'coco', 'cott',
       'cow_p', 'grou', 'lent', 'maiz', 'ocer', 'ofib', 'oilp', 'ooil', 'opul',
       'orts', 'pige', 'plnt', 'pmil', 'pota', 'rape', 'rcof', 'rest', 'rice',
       'sesa', 'smil', 'sorg', 'soyb', 'sugb', 'sugc', 'sunf', 'swpo', 'teas',
       'temf', 'toba', 'trof', 'vege', 'whea', 'yams'])
input_subset.head()

,acof,bana,barl,bean,cass,chic,cnut,coco,cott,cow_p,...,sugc,sunf,swpo,teas,temf,toba,trof,vege,whea,yams
0,0.0,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0.0,0.0,0.0,0.000000,0.0000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
4,0.0,0.0,0.0,195.300003,15221.7002,0.0,0.0,0.0,1.7,0.0,...,5.9,0.0,145.300003,0.0,0.0,0.0,6.6,451.299988,0.0,0.0

In [9]:
#residue-product-ratio (RPR)
#suggestion:maybe make this column as a seperate excel sheet and import as a dataframe
#REFERENCES:
    #Khatiwada, D., Purohit, P., Ackom, E.K., 2019. Mapping Bioenergy Supply and Demand in Selected Least Developed Countries (LDCs): Exploratory Assessment of Modern Bioenergyâ€™s Contribution to SDG7. Sustainability 11, e7091. https://doi.org/Khatiwada D, Purohit P <http://pure.iiasa.ac.at/view/iiasa/239.html> ORCID: https://orcid.org/0000-0002-7265-6960 <https://orcid.org/0000-0002-7265-6960>, & Ackom EK  (2019).  Mapping Bioenergy Supply and Demand in Selected Least Developed Countries (LDCs): Exploratory Assessment of Modern Bioenergyâ€™s Contribution to SDG7.   Sustainability 11 (24): e7091. DOI:10.3390/su11247091 <https://doi.org/10.3390/su11247091>.
    #Okello, C., Pindozzi, S., Faugno, S., Lorenzo, B., 2013. Bioenergy potential of agricultural and forest residues in Uganda. Biomass Bioenergy 56. https://doi.org/10.1016/j.biombioe.2013.06.003
    #http://www.fao.org/3/AD576E/ad576e00.pdf
#assumptions:
#beans,lentils,peas=pulses ; othercereals==barley
#other fibre=jute ; otheroilcrops==palm oil ;other roots,yam ==potatoes
#plantain==banana ;rapeseed,sunflower==groudnut; restofcrops=2; rapeseed==groudnut

acof=1
bana=2
barl=1.3
bean=1.4
cass=0.88
chic=1.4
cnut=1.6
#coco
cott=1.1
cow_p=2.9
grou=2.1
lent=1.4
maiz=2.5
ocer= 1.3
ofib=2
oilp=0.24
ooil=0.24
opul=1.4
orts=0.25
pige=5
plnt=2
pmil=1.4
pota=0.25
rape= 2.1
rcof=1
rest=2
rice=1.8
sesa=2
smil=1.2
sorg=1.4
soyb=2.66
sugb=0.7
sugc=0.4
sunf=2.1
swpo=0.25
#teas=
temf=2
toba=0.2
trof=2
vege=1
whea=1.6
yams=0.25

In [10]:
#compute the residuals in tonnes. The unit is stated here:https://www.mapspam.info/methodology/
input_subset['acof']=input_subset['acof']*acof
input_subset['bana']=input_subset['bana']*bana
input_subset['barl']=input_subset['barl']*barl
input_subset['bean']=input_subset['bean']*bean
input_subset['cass']=input_subset['cass']*cass
input_subset['chic']=input_subset['chic']*chic
input_subset['cnut']=input_subset['cnut']*cnut
input_subset['cott']=input_subset['cott']*cott
input_subset['cow_p']=input_subset['cow_p']*cow_p
input_subset['grou']=input_subset['grou']*grou
input_subset['lent']=input_subset['lent']*lent
input_subset['maiz']=input_subset['maiz']*maiz
input_subset['ocer']=input_subset['ocer']*ocer
input_subset['ofib']=input_subset['ofib']*ofib
input_subset['oilp']=input_subset['oilp']*oilp
input_subset['ooil']=input_subset['ooil']*ooil
input_subset['opul']=input_subset['opul']*opul
input_subset['orts']=input_subset['orts']*orts
input_subset['pige']=input_subset['pige']*pige
input_subset['plnt']=input_subset['plnt']*plnt
input_subset['pmil']=input_subset['pmil']*pmil
input_subset['pota']=input_subset['pota']*pota
input_subset['rape']=input_subset['rape']*rape
input_subset['rcof']=input_subset['rcof']*rcof
input_subset['rest']=input_subset['rest']*rest
input_subset['rice']=input_subset['rice']*rice
input_subset['sesa']=input_subset['sesa']*sesa
input_subset['smil']=input_subset['smil']*smil
input_subset['sorg']=input_subset['sorg']*sorg
input_subset['soyb']=input_subset['soyb']*soyb
input_subset['sugb']=input_subset['sugb']*sugb
input_subset['sugc']=input_subset['sugc']*sugc
input_subset['sunf']=input_subset['sunf']*sunf
input_subset['swpo']=input_subset['swpo']*swpo
input_subset['temf']=input_subset['temf']*temf
input_subset['toba']=input_subset['toba']*toba
input_subset['trof']=input_subset['trof']*trof
input_subset['vege']=input_subset['vege']*vege
input_subset['whea']=input_subset['whea']*whea
input_subset['yams']=input_subset['yams']*yams

In [11]:
#adding the technical potential in tonnes 
technical_potential=input_subset['technical_potential']=input_subset.sum(axis=1)
print("The total bioenergy technical potential in {} is {:.3f} million tonnes".format(country,(technical_potential.sum(axis=0))/1000000))

The total bioenergy technical potential in Somalia is 32.969 million tonnes

In [17]:
#calculation for bioelectricty potential
annual_full_load_hours =5600    #unit is hours
specific_biomass=0.00121           #unit is ton/kWh
specific_bagasse=0.0016            #unit is ton/kWh
elec_potential_coefficient=0.2  #assumption for agricultiral residues available for electricity production in the least developing countries
capacity_factor_biomass=0.8
capacity_factor_bagasse=0.53
biomass_subset=df(input_subset,columns= ['acof', 'bana', 'barl', 'bean', 'cass', 'chic', 'cnut', 'coco', 'cott',
       'cow_p', 'grou', 'lent', 'maiz', 'ocer', 'ofib', 'oilp', 'ooil', 'opul',
       'orts', 'pige', 'plnt', 'pmil', 'pota', 'rape', 'rcof', 'rest', 'rice',
       'sesa', 'smil', 'sorg', 'soyb', 'sunf', 'swpo', 'teas',
       'temf', 'toba', 'trof', 'vege', 'whea', 'yams'])
#bagasse_subset=df(input_subset,columns=['sugb', 'sugc']) --this was not used
biomass_subset[:] *=(elec_potential_coefficient/specific_biomass)
bioelec_potential_kWh=biomass_subset['bioelec_potential_kWh']=biomass_subset.sum(axis=1)
print("The total bioelectricity potential in {} is {:.3f} TWh".format(country,(bioelec_potential_kWh.sum(axis=0))/1000000000))

The total bioelectricity potential in Somalia is 5.065 TWh

In [18]:
#adding the bioelectricy_potential column to the original dataset and dropping the infomation of the individual criops
input=df(input,columns=['Country','NightLights', 'Pop', 'id', 'GridCellArea', 'ElecPop', 'WindVel', 'GHI',
       'TravelHours', 'Elevation', 'Slope', 'ResidentialDemandTIerCustom',
       'LandCover', 'SubstationDist', 'CurrentHVLineDist', 'CurrentMVLineDist',
       'RoadDist', 'X_deg', 'Y_deg', 'TransformerDist', 'PlannedMVLineDist',
       'PlannedHVLineDist', 'HydropowerDist', 'Hydropower', 'HydropowerFID','bioelec_potential_kWh'])
input['bioelec_potential_kWh']=biomass_subset['bioelec_potential_kWh']

input.head()

,Country,NightLights,Pop,id,GridCellArea,ElecPop,WindVel,GHI,TravelHours,Elevation,...,RoadDist,X_deg,Y_deg,TransformerDist,PlannedMVLineDist,PlannedHVLineDist,HydropowerDist,Hydropower,HydropowerFID,bioelec_potential_kWh
0,Somalia,0.0,65.015217,8956,0.013,0.0,7.573399,2254.000000,6.650000,9.179685,...,68.808,41.591873,-1.638938,0,99,260.723,60.786195,6833.36,148,0.000000e+00
1,Somalia,0.0,14368.362920,10117,0.906,0.0,7.415857,2252.768695,6.619415,4.779344,...,67.994,41.583711,-1.635665,0,99,260.798,60.746018,6833.36,148,0.000000e+00
2,Somalia,0.0,195.045650,8954,0.053,0.0,7.197120,2250.000000,6.550000,6.000000,...,66.918,41.584602,-1.623196,0,99,259.518,59.416609,6833.36,148,0.000000e+00
3,Somalia,0.0,32.507608,878,0.009,0.0,7.674210,2246.000000,6.450000,11.000000,...,65.931,41.603072,-1.598332,0,99,256.143,56.135373,6833.36,148,0.000000e+00
4,Somalia,0.0,130.030434,10111,0.018,0.0,7.490109,2245.000000,6.366667,8.000000,...,65.340,41.612651,-1.583745,0,99,254.225,54.263725,6833.36,148,2.407642e+06

In [19]:
#input['bio_new']= input['bioelec_potential_kWh'].divide(annual_full_load_hours) 
#input.head()

In [20]:
output='Somalia'

In [21]:
messagebox.showinfo('OnSSET', 'Browse to the folder where you want to save the outputs')
output_dir = filedialog.askdirectory()
output_dir_output = os.path.join(output_dir, '{}_Results.csv'.format(output))

In [22]:
# Returning the result as a csv file
input.to_csv(output_dir_output, index=False)